defaultBaseImage: gcr.io/distroless/static-debian12:nonroot
builds:
  - id: profgate
    main: ./cmd/profgate
    ldflags:
      - -s -w -X main.version={{.Env.VERSION}}
  - id: testapp
    main: ./test/e2e/testapp
