apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: profgate
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: profgate
subjects:
  - kind: ServiceAccount
    name: profgate
    namespace: profgate
